Refractor dialog
Tencent/tdesign-common pull request #1250
Opened 2023-04-05 12:41 UTC by tangzixuan

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [x] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- fix(组件名称): 处理问题或特性描述 ...

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2023-04-05 12:41 UTC, tangzixuan commented
* 相关联的pr参考： https://github.com/Tencent/tdesign-mobile-vue/pull/564

2023-04-13 06:48 UTC, LeeJim requested changes

2023-04-13 06:48 UTC, LeeJim commented on style/mobile/components/dialog/v2/_index.less
> +  &__close--btn {
这个不符合 BEM 规范，原来是正确的

2023-04-13 06:48 UTC, LeeJim commented on style/mobile/components/dialog/v2/_index.less
> +    // top: 16rpx;
可以直接移除，不需要注释；下面的同理

2023-04-13 10:59 UTC, tangzixuan commented on style/mobile/components/dialog/v2/_index.less
> +  &__close--btn {
已修复

2023-04-13 10:59 UTC, tangzixuan commented on style/mobile/components/dialog/v2/_index.less
> +    // top: 16rpx;
已修复

2023-04-14 07:49 UTC, LeeJim approved these changes

2023-04-14 07:50 UTC, merged