fix(menu): disabled attribute does not take effect
Tencent/tdesign-common pull request #1273
Opened 2023-04-14 15:24 UTC by wangyang0210

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue
[tdesign-vue-next #2690](https://github.com/Tencent/tdesign-vue-next/issues/2690)

### 💡 需求背景和解决方案

### 📝 更新日志

fix(menu): 修复disabled属性在expandType为popup时样式不生效

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2023-04-20 07:16 UTC, xiaosansiji commented
感觉可以通过调整下 disable 样式出现在 less 文件中的顺序来调整下？加 `!important` 破坏了整体样式代码可读性（不能顺序向下决定优先级）也可能会导致用户覆盖样式补方便

2023-04-20 08:11 UTC, uyarn requested changes

2023-04-20 08:11 UTC, uyarn commented on style/web/components/menu/_index.less
> +      color: @menu-item-disabled-color !important;
有点暴力 一般不会用这么高优先级的方式修复

2023-04-20 15:01 UTC, wangyang0210 commented on style/web/components/menu/_index.less
> +      color: @menu-item-disabled-color !important;
最开始的时候是想调整优先级或者使用@layer来进行调整的，然后看了下其他的代码中有用`!important`就直接使用了，我来调整下吧；

2023-04-25 11:38 UTC, uyarn approved these changes

2023-04-25 11:38 UTC, merged