tabs docs and style update
Tencent/tdesign-common pull request #1314
Opened 2023-04-27 09:22 UTC by TeacherDingTing

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- fix(组件名称): 处理问题或特性描述 ...

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2023-05-09 09:38 UTC, LeeJim requested changes
改错了，api 要 api_v2 的才对

2023-05-18 08:49 UTC, anlyyao approved these changes

2023-05-18 08:54 UTC, LeeJim requested changes

2023-05-18 08:54 UTC, LeeJim commented on style/mobile/components/tabs/v2/_index.less
> +&.@{prefix}-size-m {
尽量不要用额外的修饰类名，统一 BEM 写法。
`t-tabs--size-m`

2023-05-18 08:56 UTC, LeeJim approved these changes

2023-05-18 08:56 UTC, merged