fix(Menu): Menu side logo style lack docs Menu side logo style
Tencent/tdesign-common pull request #1602
Opened 2023-09-22 02:35 UTC by Zzongke

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [x] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue
Closed [3407](https://github.com/Tencent/tdesign-vue-next/issues/3407)

### 💡 需求背景和解决方案
Menu side logo style lack docs Menu side logo style

### 📝 更新日志

- fix(Menu): 修复菜单侧Logo切换的样式缺失，和官网展示一致。

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2023-09-22 13:23 UTC, uyarn commented on style/web/components/menu/_index.less
> +    margin-left: 24px;
这个也用对应的margin variables替换比较好

2023-09-22 13:24 UTC, uyarn requested changes
如果补充了这个 docs的相关代码就移除吧
https://github.com/Tencent/tdesign-common/blob/develop/style/web/components/menu/_docs.less#L81

2023-09-22 15:13 UTC, Zzongke commented on style/web/components/menu/_index.less
> +    margin-left: 24px;
👌

2023-09-23 05:28 UTC, Zzongke commented on style/web/components/menu/_index.less
> +    margin-left: 24px;
uyarn，改好用margin cariables替换了。😊

2023-09-26 03:29 UTC, Zzongke reviewed
done.

2023-09-26 03:30 UTC, Zzongke commented
> 如果补充了这个 docs的相关代码就移除吧 https://github.com/Tencent/tdesign-common/blob/develop/style/web/components/menu/_docs.less#L81

done.

2023-09-26 08:05 UTC, uyarn approved these changes

2023-09-26 08:06 UTC, merged