Feat/upload
Tencent/tdesign-common pull request #308
Opened 2022-03-16 01:06 UTC by alamozhou

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- fix(组件名称): 处理问题或特性描述 ...

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2022-03-16 01:19 UTC, josonyang requested changes

2022-03-16 01:19 UTC, josonyang commented on docs/mobile/api/upload.md
> +::: demo demos/baseSingle
公共部分的语法是{{ base}}，并且全部小写格式

2022-03-16 01:19 UTC, josonyang commented on docs/mobile/api/upload.md
> +## API
API的部分放到组件库的文档里，请参考下其他组件的组织方式

2022-03-16 01:19 UTC, josonyang commented on style/mobile/components/upload/_index.less
> +        &:hover {
移动端的hover不需要吧

2022-03-23 00:16 UTC, ZhangDaZongWei commented
@josonyang 你好，请关注下这个 pr，mobile react 端需要使用。

2022-03-24 06:14 UTC, josonyang approved these changes
LGTM

2022-03-24 06:14 UTC, merged