移除notification组件vue3分支中的transition写法，添加一个notification-list的类名
Tencent/tdesign-common pull request #450
Opened 2022-05-09 07:26 UTC by qunbotop

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- fix(组件名称): 处理问题或特性描述 ...

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2022-05-09 10:52 UTC, uyarn commented
这个改动看起来也会影响到其他框架 直接合入其他框架会受影响

2022-05-09 10:52 UTC, uyarn requested changes
这个改动看起来也会影响到其他框架 直接合入其他框架会受影响

2022-05-10 06:33 UTC, pengYYYYY commented
> 这个改动看起来也会影响到其他框架 直接合入其他框架会受影响
之前单独在 vue3 用的，可以删除

2022-05-10 06:41 UTC, pengYYYYY commented
```css
&-list__show {
    position: fixed;
  }
```
为增加的类名，vue2与react都没有对这个类名的引用

2022-05-10 06:43 UTC, pengYYYYY approved these changes

2022-05-10 09:13 UTC, uyarn approved these changes

2022-05-10 09:13 UTC, merged