style: collapse 间隔线
Tencent/tdesign-common pull request #522
Opened 2022-06-14 13:33 UTC by laishiwen

fix #180

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [x] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- fix(组件名称): 处理问题或特性描述 ...

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2022-06-14 13:34 UTC, laishiwen commented
collapse 样式更改

2022-06-14 14:04 UTC, LeeJim requested changes

2022-06-14 14:04 UTC, LeeJim commented on style/mobile/components/collapse/_index.less
> +    width: 95%;
百分比是动态的，用绝对值吧。
left: 16px 就好了

2022-06-14 14:04 UTC, LeeJim commented on style/mobile/components/collapse/_index.less
> +    background: #eee;
边框颜色用 @gray-color-3 这个变量

2022-06-14 14:55 UTC, laishiwen commented on style/mobile/components/collapse/_index.less
> +    width: 95%;
done

2022-06-14 14:56 UTC, laishiwen commented on style/mobile/components/collapse/_index.less
> +    background: #eee;
done

2022-06-15 02:02 UTC, LeeJim approved these changes
LGTM

2022-06-15 02:11 UTC, merged