fix: 修复react mobile input样式、两行显示、分隔符问题
Tencent/tdesign-common pull request #548
Opened 2022-06-19 12:26 UTC by yilaierwang

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

fix: [135](https://github.com/TDesignOteam/tdesign-mobile-react/issues/135)
### 💡 需求背景和解决方案

### 📝 更新日志

- fix(Input): 修复input样式、两行显示、分隔符问题

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2022-06-20 03:17 UTC, LeeJim requested changes

2022-06-20 03:17 UTC, LeeJim commented on style/mobile/components/input/_index.less
> +  &__twoLines {
命名有点问题，不要用驼峰，另外语义不好，建议使用 `vertical`

2022-06-20 03:38 UTC, yilaierwang commented on style/mobile/components/input/_index.less
> +  &__twoLines {
done

2022-06-20 13:16 UTC, LeeJim commented on style/mobile/components/input/_index.less
> +    &--suffixSeperate {
这个分割线，最好在 demo 里实现，不需要内嵌组件里

2022-06-21 01:37 UTC, yilaierwang commented on style/mobile/components/input/_index.less
> +    &--suffixSeperate {
可以， 这也看不出 哪些 是在组件内， 哪些是demo呀

2022-06-21 07:18 UTC, LeeJim commented on style/mobile/components/input/_index.less
> +    &--suffixSeperate {
写在这里就是组件内部的，写在 demo 里的 style 则是 demo的

2022-06-22 15:56 UTC, yilaierwang commented on style/mobile/components/input/_index.less
> +    &--suffixSeperate {
不是这个意思，是不知道issue的问题哪些是demo的，哪些是组件的
没关系， 改好了，你看一下

2022-06-23 06:25 UTC, LeeJim approved these changes
LGTM

2022-06-23 06:25 UTC, merged

2022-06-23 06:27 UTC, LeeJim commented on style/mobile/components/input/_index.less
> +    &--suffixSeperate {
哦哦。其实就是通过对组件的结构设计来看的，理解组件的结构就明白了