fix(message):message组件修复样式
Tencent/tdesign-common pull request #552
Opened 2022-06-20 03:26 UTC by wwlh200

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [x] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

https://github.com/TDesignOteam/tdesign-mobile-react/issues/160
https://github.com/TDesignOteam/tdesign-mobile-react/issues/159
### 💡 需求背景和解决方案

### 📝 更新日志

- fix(组件名称): 处理问题或特性描述 ...

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2022-06-20 12:47 UTC, LeeJim approved these changes
LGTM

2022-06-20 13:21 UTC, LeeJim requested changes

2022-06-20 13:21 UTC, LeeJim commented on style/mobile/components/message/_index.less
> +  &--close-btn{
需要空格

2022-06-21 02:55 UTC, wwlh200 commented on style/mobile/components/message/_index.less
> +  &--close-btn{
ok

2022-06-22 07:34 UTC, LeeJim approved these changes

2022-06-22 07:36 UTC, merged