style(radio): update style
Tencent/tdesign-common pull request #560
Opened 2022-06-22 01:13 UTC by anlyyao

### 🤔 这个 PR 的性质是？
- [x] 组件样式/交互改进

### 📝 更新日志
- style(radio): 调整移动端radio样式

2022-06-23 06:29 UTC, LeeJim requested changes

2022-06-23 06:29 UTC, LeeJim commented on style/mobile/components/radio/_index.less
> +      width: calc(100% - 40px);
使用 `left: 40` 替代 calc 吧

2022-06-23 06:29 UTC, LeeJim commented on style/mobile/components/radio/_index.less
> +      width: calc(100% - 40px);
同上

2022-06-25 07:31 UTC, LeeJim commented
问题修复完就可以合并了

2022-06-27 03:05 UTC, anlyyao commented on style/mobile/components/radio/_index.less
> +      width: calc(100% - 40px);
已调整。

2022-06-27 03:05 UTC, anlyyao commented on style/mobile/components/radio/_index.less
> +      width: calc(100% - 40px);
已调整。

2022-06-27 07:10 UTC, LeeJim approved these changes

2022-06-27 07:10 UTC, merged