feat: rate 组件
Tencent/tdesign-common pull request #602
Opened 2022-06-30 08:13 UTC by RedDevi1s

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

feat: rate 组件

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2022-06-30 08:29 UTC, HQ-Lin commented on docs/web/api/rate.md
> +#### 24px
这里用size 一个demo表示就好了，不要拆那么多demo

2022-06-30 08:46 UTC, honkinglin commented on docs/web/api/rate.md
> +{{ unrate }}
这里状态也整合起来吧，用status表示，可以demo里面加描述区分状态

2022-06-30 09:51 UTC, uyarn commented on style/web/components/rate/_var.less
> +
颜色相关的要用token替换 麻烦参考一下其他组件的__var.less

2022-06-30 09:51 UTC, uyarn requested changes
颜色相关的要用token替换 麻烦参考一下其他组件的__var.less

2022-07-01 06:44 UTC, RedDevi1s commented on docs/web/api/rate.md
> +#### 24px
done

2022-07-01 06:44 UTC, RedDevi1s commented on docs/web/api/rate.md
> +{{ unrate }}
done

2022-07-01 06:44 UTC, RedDevi1s commented on style/web/components/rate/_var.less
> +
done

2022-07-01 06:57 UTC, RedDevi1s commented
> 颜色相关的要用token替换 麻烦参考一下其他组件的__var.less

done

2022-07-01 07:45 UTC, uyarn approved these changes

2022-07-01 07:46 UTC, merged