feat(image-viewer): 重构 image-viewer 组件
Tencent/tdesign-common pull request #684
Opened 2022-07-31 13:46 UTC by ruige24601

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [x] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- fix(组件名称): 处理问题或特性描述 ...

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2022-08-08 07:47 UTC, LeeJim requested changes

2022-08-08 07:47 UTC, LeeJim commented on style/mobile/components/image-viewer/_index.less
> +    -ms-flex-negative: 0;
这个应该不需要手动加入，构建的时候会自动判断是否需要兼容

2022-08-10 07:03 UTC, ruige24601 commented on style/mobile/components/image-viewer/_index.less
> +    -ms-flex-negative: 0;
已修复

2022-08-12 07:55 UTC, LeeJim approved these changes

2022-08-12 07:55 UTC, merged