feat(Calendar): 完成Calendar组件样式
Tencent/tdesign-common pull request #706
Opened 2022-08-05 16:00 UTC by LadyChatterleyLover

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ x] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

https://github.com/Tencent/tdesign-mobile-vue/issues/260
### 💡 需求背景和解决方案
新增Calendar组件

### 📝 更新日志

- fix(组件名称): 处理问题或特性描述 ...

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x ] 文档已补充或无须补充
- [ x] 代码演示已提供或无须提供
- [ x] TypeScript 定义已补充或无须补充
- [ x] Changelog 已提供或无须提供

2022-08-08 07:54 UTC, LeeJim requested changes

2022-08-08 07:54 UTC, LeeJim commented on style/mobile/components/calendar/_index.less
> +.cc-calendar {
前缀要用 prefix，可以参考其他组件

2022-08-08 07:54 UTC, LeeJim commented on style/mobile/components/calendar/_index.less
> +  &-text {
应该是 `__text`

2022-08-08 07:54 UTC, LeeJim commented on style/mobile/components/calendar/_index.less
> +    &-current {
应该是 `--current`

2022-08-08 07:54 UTC, LeeJim commented on style/mobile/components/calendar/_index.less
> +  &-text {
其他同理，记得修改下。

2022-08-08 07:54 UTC, LeeJim commented on style/mobile/components/calendar/_index.less
> +          color: #c8c9cc !important;
避免使用 `important`

2022-08-08 07:55 UTC, LadyChatterleyLover commented
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/tdesign-common"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月8日(星期一) 下午3:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tencent/tdesign-common] feat(Calendar): 完成Calendar组件样式 (PR #706)





 
@LeeJim requested changes on this pull request.
 
 
In style/mobile/components/calendar/_index.less:
 &gt; @@ -0,0 +1,107 @@ +.cc-calendar {  
前缀要用 prefix，可以参考其他组件
 
 
In style/mobile/components/calendar/_index.less:
 &gt; +  background: #fff; +  overflow-x: hidden; + +  &amp;-title { +    display: flex; +    align-items: center; +    justify-content: center; +    font-size: 16px; +    font-weight: 500; +    background-color: #fff; +    color: #303133; +    width: 100%; +    height: 44px; +  } + +  &amp;-text {  
应该是 __text
 
 
In style/mobile/components/calendar/_index.less:
 &gt; +    font-weight: 500; +    background-color: #fff; +    color: #303133; +    width: 100%; +    height: 44px; +  } + +  &amp;-text { +    display: flex; +    align-items: center; +    justify-content: center; +    font-size: 14px; +    margin-top: 10px; +    margin-bottom: 15px; + +    &amp;-current {  
应该是 --current
 
 
In style/mobile/components/calendar/_index.less:
 &gt; + +    &amp;-item { +      flex: 1; +      display: flex; +      align-items: center; + +      &amp;-text { +        flex: 1; +        display: flex; +        align-items: center; +        justify-content: center; +        font-size: 14px; +        border-radius: 8px; + +        &amp;-nocurrent { +          color: #c8c9cc !important;  
避免使用 important
 
 
In style/mobile/components/calendar/_index.less:
 &gt; +  background: #fff; +  overflow-x: hidden; + +  &amp;-title { +    display: flex; +    align-items: center; +    justify-content: center; +    font-size: 16px; +    font-weight: 500; +    background-color: #fff; +    color: #303133; +    width: 100%; +    height: 44px; +  } + +  &amp;-text {  
其他同理，记得修改下。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2022-08-29 10:32 UTC, josonyang approved these changes
LGTM

2022-08-29 10:32 UTC, josonyang approved these changes
LGTM

2022-08-29 10:35 UTC, LeeJim approved these changes

2022-08-29 10:35 UTC, merged