fix(steps): 设置icon图标与标题行高一致。
Tencent/tdesign-common pull request #851
Opened 2022-09-20 13:54 UTC by Micro-sun

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

https://github.com/Tencent/tdesign-vue/issues/1486

### 💡 需求背景和解决方案

### 📝 更新日志

fix(steps): 设置icon图标与标题行高一致。

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2022-09-22 06:25 UTC, uyarn commented on style/web/components/breadcrumb/_index.less
> +      .@{prefix}-icon {
icon不要用prefix

2022-09-22 09:39 UTC, Micro-sun commented on style/web/components/breadcrumb/_index.less
> +      .@{prefix}-icon {
已改回t-icon。

2022-09-23 02:39 UTC, uyarn requested changes
携带了与这个改动不相关的修改 麻烦rebase一下再推上来。

2022-09-23 08:53 UTC, xiaosansiji commented on style/web/components/table/_index.less
> -    padding: 16px 0;
这里是否不应该修改的？

2022-09-26 02:42 UTC, xiaosansiji approved these changes

2022-09-26 02:44 UTC, Micro-sun commented on style/web/components/table/_index.less
> -    padding: 16px 0;
这里是rebase develop的内容，挺好奇为啥PR这里也会出现。

2022-09-26 07:30 UTC, uyarn approved these changes

2022-09-26 07:30 UTC, merged