Hotfix/select
Tencent/tdesign-common pull request #856
Opened 2022-09-22 03:22 UTC by quqianyu

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 [相关 Issue](https://github.com/Tencent/tdesign/issues/226)

### 💡 需求背景和解决方案
优化select图标大小为16px*16px ；中尺寸option的ling-height修改为22px；自定义下拉面板的textarea新增padding

### 📝 更新日志

- fix(组件名称): 处理问题或特性描述 ...

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2022-09-22 06:24 UTC, uyarn commented on style/web/components/select/_index.less
> +.@{prefix}-icon.@{prefix}-icon-browse {
icon不要用prefix 就写t就行了

2022-09-22 06:24 UTC, uyarn requested changes

2022-09-22 06:24 UTC, uyarn commented on style/web/components/select/_index.less
> +.@{prefix}-icon.@{prefix}-icon-browse {
icon不要用prefix 就写t就行了

2022-09-22 12:58 UTC, quqianyu reviewed
1

2022-09-23 02:28 UTC, xiaosansiji approved these changes

2022-09-23 02:35 UTC, uyarn commented on style/web/components/select/_index.less
> +
又看了一下你这里是修复suffix icon的大小 
1. 不能写在这里 放在最外层 这样会造成污染 全局的icon样式都会被这个污染
2. 图标大小是1em 1em 直接通过修改父节点的fontsize就可以满足需求了 把suffix的节点的fontsize改成16就行。

2022-09-23 02:37 UTC, uyarn commented on style/web/components/select/_index.less
> +}
这里也是 这样会对全局的textarea都造成污染的 而且还用了!important权重太高了
其实这里你要改的应该只是demo里的textarea 没有通用性 应该在demo里单独多个style处理

2022-09-26 07:57 UTC, uyarn commented on style/web/components/select/_docs.less
> +}
这个是指在具体的demo加 这样还是会污染其他不受影响的组件的

2022-09-26 08:13 UTC, uyarn commented on style/web/components/select/_docs.less
> +}
我直接删掉了 @quqianyu 有时间的话麻烦到主仓库对应的demo里面的textarea增加这个样式即可。

2022-09-26 08:30 UTC, uyarn approved these changes

2022-09-26 08:30 UTC, merged

2022-09-26 08:48 UTC, quqianyu commented on style/web/components/select/_docs.less
> +}
那这个eslint错误是因为这个文件 删掉的话 就不用管了吗