fix(loading): update loading adapt logic
Tencent/tdesign-common pull request #900
Opened 2022-10-13 13:24 UTC by anlyyao

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复

### 📝 更新日志

- fix(loading): loading自适应逻辑增加移动端判断

2022-10-14 02:33 UTC, LeeJim requested changes

2022-10-14 02:33 UTC, LeeJim commented on js/loading/circle-adapter.ts
> +  if ((isSafari && !isMobile) || (isIosWechat && !isMobile)) {
改成 `(isSafari  || isIosWechat) && !isMobile` 会简单明了一些。

2022-10-14 03:06 UTC, anlyyao commented on js/loading/circle-adapter.ts
> +  if ((isSafari && !isMobile) || (isIosWechat && !isMobile)) {
已改～

2022-10-21 07:37 UTC, LeeJim approved these changes

2022-10-21 07:37 UTC, merged